module("ili9xxx.py", base_path=".", opt=3)
module("st77xx.py", base_path=".", opt=3)
module("st7735.py", base_path=".", opt=3)
module("st7789.py", base_path=".", opt=3)
module("ili9341.py", base_path=".", opt=3)
